version: "3.5"
services:
  dailystoic:
    image: "dailystoic.dailystoic.public.dappnode.eth:0.1.0"
    build:
      context: .
    restart: unless-stopped
    volumes:
      - "quotes:/quotes"
volumes:
  quotes: {}
